---

title: "analisis_senderos_educacion"
author: "Francisco Meneses - CIAE"
date: "2023-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Cargar paquetes 

```{r}
# Instalar pacman si no está instalado
if (!requireNamespace("pacman", quietly = TRUE)) {
  install.packages("pacman")
}

# Cargar el paquete dplyr utilizando pacman::p_load
pacman::p_load(dplyr,haven, readxl,lavaan,semPlot)
```


## Cargar datos


```{r}
muestra_2018_educacion <- read_excel("input/muestra_2018_educacion.xlsx")

```


```{r}
muestra_2018_educacion=muestra_2018_educacion %>% na.omit()


```

## Analisis path

```{r}


model <- '  ptje_lect2m_alu ~ ingreso_percapita '

fit <- lavaan::sem(model, data = muestra_2018_educacion) #calcular 
summary(fit, standardized = TRUE, fit.measures = TRUE) 


semPaths(fit,   whatLabels = "std",
           sizeMan = 15,
           edge.label.cex = 1.15,
           style = "ram",
           nCharNodes = 0, nCharEdges = 0)


model <- '  ptje_lect2m_alu ~ ptje_lect2m_alu_colegio + apoyo_escolar 
ptje_lect2m_alu_colegio ~ ingreso_percapita
apoyo_escolar ~ ingreso_percapita 


'

fit2 <- lavaan::sem(model, data = muestra_2018_educacion) #calcular 
summary(fit2, standardized = TRUE, fit.measures = TRUE, rsquare=T) 



semPaths(fit2, whatLabels = "std",
           sizeMan = 15,
           edge.label.cex = 1.15,
           style = "ram",
           nCharNodes = 0, nCharEdges = 0, layout= "tree2")
```



